In [19]:
import numpy as np

arr = np.random.rand(5)
type(arr)

numpy.ndarray

In [22]:
# np.random.rand((5, 2)) - ошибка tuple
np.random.rand(*(5, 2))


np.random.rand(5, 2)



array([[0.15348442, 0.96238357],
       [0.82146101, 0.32499074],
       [0.35671001, 0.50584253],
       [0.86406203, 0.25865763],
       [0.68728638, 0.5993269 ]])

In [34]:
np.random.uniform(-102, -100, (3, 4))

array([[-100.17852994, -101.54779659, -100.3488885 , -100.53864456],
       [-101.35143534, -100.2846306 , -100.73957635, -100.32754156],
       [-101.33433316, -101.5650347 , -101.97236609, -101.48320191]])

In [52]:
np.random.randint(5, 7, size=(2, 2))

array([[6, 6],
       [5, 5]])

In [57]:
arr = np.arange(6)
print(arr)
np.random.shuffle(arr)
arr

[0 1 2 3 4 5]


array([1, 3, 2, 0, 5, 4])

In [63]:
arr = np.arange(6)
print(arr)

arr2 = np.random.permutation(arr)
print(arr2)

[0 1 2 3 4 5]
[2 0 3 5 1 4]


In [76]:
arr = ['Eduard', 'Lyuda', 'Vika', 'Irina']
arr3 = tuple()
arr3 = ('Ed', 'Lyuda', 'Minnibaev')
print(arr3)
arr2 = np.random.permutation(arr3)
print(arr2)

('Ed', 'Lyuda', 'Minnibaev')
['Ed' 'Minnibaev' 'Lyuda']


In [99]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

choice = np.random.choice(workers, size=10, replace=True)
choice

array(['Kate', 'Ivan', 'Nikita', 'Maria', 'Nikita', 'John', 'Ivan',
       'John', 'Ivan', 'Nikita'], dtype='<U6')

In [102]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]
np.random.seed()
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]
np.random.seed()
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]
[3 1 5]
[3 3 6]
[4 4 0]
[8 8 3]
[7 7 0]
[4 2 5]
[7 3 3]
[0 2 5]
[5 6 1]


In [109]:
np.random.seed(2021)

simple = np.random.rand()
print(simple)

randoms = np.random.uniform(-150, 2021, 120)
# print(randoms)

table = np.random.randint(1, 101, (3, 2))
print('Печатаем table\n', table)

even = np.arange(2, 17, 2)
print(even)

# mix = np.random.permutation(even)
mix = np.array(even)
print(mix)

np.random.shuffle(mix)
print(mix)
print(even)

select = np.random.choice(even, size=3, replace=False)
print(select)

triplet = np.random.permutation(select)
print(triplet)

0.6059782788074047
Печатаем table
 [[46 93]
 [35 41]
 [17 45]]
[ 2  4  6  8 10 12 14 16]
[ 2  4  6  8 10 12 14 16]
[ 6 10  2  8 14 16  4 12]
[ 2  4  6  8 10 12 14 16]
[14  2  4]
[ 2  4 14]


In [149]:
def get_chess(a):
    arr = np.zeros((a, a))
    if a == 1:
        return arr
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

print(get_chess(5))

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [172]:
array = [1, 2, 3, 4, 5]
def shuffle_seed(array):
    rand_seed = np.random.randint(2**32 - 1, dtype='uint32')
    np.random.seed(rand_seed)
    return np.random.permutation(array), rand_seed

# np.random.randint(2**32 - 1, dtype='uint32')
print(shuffle_seed(array))
x, y = shuffle_seed(array)
y

(array([1, 3, 4, 2, 5]), 3155847309)


736081126

In [181]:
# def min_max_dist(*vectors):
#     # vec_dist = np.zeros(len(vectors)**2)
#     dists = list()
#     max_dist = 0
#     min_dist = np.linalg.norm(vectors[1] - vectors[0])
#     for i in range(len(vectors)):
#         for j in range(i + 1, len(vectors)):
#             if vec1 is vectors[j]:
#                 continue
#             temp = np.linalg.norm(vec1 - vectors[j])
#             max_dist = temp if temp > max_dist else max_dist
#             min_dist = temp if temp < min_dist else min_dist
#     return (min_dist, max_dist)

def min_max_dist(*vectors):
    dists = list()
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dists.append(np.linalg.norm(vectors[j] - vectors[i]))
    return (min(dists), min(dists))


vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

print(min_max_dist(vec1, vec2, vec3))

        
            

(5.196152422706632, 5.196152422706632)


In [183]:
def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            scalar_product = np.dot(vectors[i], vectors[j])
            if scalar_product == 0:
                return True
    return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))

True


In [202]:
# def get_loto(num):
#     arr = np.random.choice(np.arange(1, 101), (num, 5, 5), replace=False)
#     return arr

def get_loto(num):
    arr = np.random.randint(1, 10, (num, 5, 5))
    return arr

get_loto(2)

array([[[6, 5, 4, 7, 8],
        [6, 2, 9, 4, 7],
        [3, 1, 4, 4, 3],
        [4, 1, 1, 4, 1],
        [9, 3, 1, 6, 9]],

       [[3, 7, 8, 1, 7],
        [2, 9, 6, 1, 7],
        [8, 1, 8, 7, 4],
        [5, 8, 5, 3, 1],
        [6, 6, 1, 7, 4]]])

In [211]:
# def get_unique_loto(num):
#     arr = np.zeros((num, 5, 5), dtype=int)
#     for i in range(num):
#         arr[i] = np.random.choice(np.arange(1, 101), size=(5, 5), replace=False)
#     return arr

def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res

get_unique_loto(3)

array([[[ 87,  63,  70,  83,  47],
        [ 80,  31,  97,  32,  40],
        [ 46,  75,  36,  37,  55],
        [ 38,  93,  79,  69,   3],
        [  9,  91,  56,  20,  14]],

       [[ 22,  66,  26,  73, 100],
        [ 21,  51,  10,   3,  97],
        [ 82,  83,   9,  63,  67],
        [ 59,  62,  69,  71,  79],
        [ 76,   6,  11,  65,   7]],

       [[ 24,  94,  41,  29, 100],
        [  9,  11,  58,  49,  65],
        [ 26,  98,  84,  38,  52],
        [ 15,  77,  10,  44,  87],
        [ 53,   7,  74,  64,  14]]])

In [215]:
simplelist = [19, 242, 14, 152, 142, 1000]

arr = np.array(simplelist)
arr.mean()
arr

array([  19,  242,   14,  152,  142, 1000])