In [17]:
import numpy as np

a = np.int8(25)
a
print(type(a))

n = np.uint32(25)
print(np.iinfo(n))

np.iinfo(np.int8)
np.iinfo(a)
b = np.int64(124)
np.iinfo(b)

c = np.int32(1000)

c = b + 1000
type(c)



<class 'numpy.int8'>
Machine parameters for uint32
---------------------------------------------------------------
min = 0
max = 4294967295
---------------------------------------------------------------



numpy.int64

In [22]:
a = np.int8(600)
a

88

In [30]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [33]:
print(np.sctypeDict)
print(len(np.sctypeDict))

{'?': <class 'numpy.bool_'>, 0: <class 'numpy.bool_'>, 'byte': <class 'numpy.int8'>, 'b': <class 'numpy.int8'>, 1: <class 'numpy.int8'>, 'ubyte': <class 'numpy.uint8'>, 'B': <class 'numpy.uint8'>, 2: <class 'numpy.uint8'>, 'short': <class 'numpy.int16'>, 'h': <class 'numpy.int16'>, 3: <class 'numpy.int16'>, 'ushort': <class 'numpy.uint16'>, 'H': <class 'numpy.uint16'>, 4: <class 'numpy.uint16'>, 'i': <class 'numpy.intc'>, 5: <class 'numpy.intc'>, 'uint': <class 'numpy.uint32'>, 'I': <class 'numpy.uintc'>, 6: <class 'numpy.uintc'>, 'intp': <class 'numpy.int64'>, 'p': <class 'numpy.int64'>, 9: <class 'numpy.int64'>, 'uintp': <class 'numpy.uint64'>, 'P': <class 'numpy.uint64'>, 10: <class 'numpy.uint64'>, 'long': <class 'numpy.int32'>, 'l': <class 'numpy.int32'>, 7: <class 'numpy.int32'>, 'ulong': <class 'numpy.uint32'>, 'L': <class 'numpy.uint32'>, 8: <class 'numpy.uint32'>, 'longlong': <class 'numpy.int64'>, 'q': <class 'numpy.int64'>, 'ulonglong': <class 'numpy.uint64'>, 'Q': <class 'n

In [48]:
np.bool_(1)
np.bool_({})

False

In [49]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [50]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [52]:
a =np.int32(20)
b = np.int16(100)
c = a + b
type(c)

numpy.int32

In [61]:
np.sctypeDict
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')


<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [62]:
np.uint8(-456)

56

In [66]:
np.finfo(np.float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [75]:
arr, step = np.linspace(-6, 21, 60, retstep=True)
step
# arr

0.4576271186440678

In [83]:
arr, step = np.linspace(1, 2, 3, endpoint=False, retstep=True)
arr

array([1.        , 1.33333333, 1.66666667])

In [106]:
arr = np.arange(8)
arr
arr.shape = (2, 4)
arr
arr.shape = (8)
arr
arr_new = arr.reshape(2, 4, order='F')
arr_new
arr_new.transpose()

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [121]:
arr = np.linspace(1, 2, 6)
arr[::-1]

array([2. , 1.8, 1.6, 1.4, 1.2, 1. ])

In [161]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
print(nd_array)
nd_array[::-1, -1]
nd_array.sort()
nd_array

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [176]:
data = np.array([4, -9, -4, 3])
roots = np.sqrt(data)
print(roots)
sum(roots)
print(np.isnan(roots))
print(np.isnan(roots))
print(roots[np.isnan(roots)])
roots[np.isnan(roots)] = 0
sum(roots)


[2.                nan        nan 1.73205081]
[False  True  True False]
[False  True  True False]
[nan nan]


C:\Users\Eduard\AppData\Local\Temp\ipykernel_6420\1239365866.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


3.732050807568877

In [193]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec3 = vec1 > vec2
vec3

array([False, False,  True, False])

In [194]:
vec1 = np.array([3, 4])
length = np.linalg.norm(vec1)
length

5.0

In [196]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [197]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0